# Generated by Django 5.0.4 on 2024-05-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git', models.URLField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('name', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('position', models.TextField(max_length=200)),
                ('detail', models.TextField(max_length=700)),
                ('cv', models.FileField(upload_to='pdf/')),
                ('about', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length='200')),
                ('Front_end', models.TextField(max_length='200')),
                ('Back_end', models.TextField(max_length='200')),
                ('Framework', models.TextField(max_length='200')),
                ('Database', models.TextField(max_length='200')),
                ('project_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=100)),
                ('skill_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
